# -*- coding: utf-8 -*-
"""HW2_REPORT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-pa1zZdHEx89RnRf-m5yIkagVNd8Se-m
"""

# HW2_hash_practice 程式執行結果報告

# 文字數量分析
total_unique_words = 10

word_frequencies = {
    "Cheese": 234,
    "Pizza": 83,
    "Coke": 145,
    "Steak": 46,
    "Burger": 196,
    "Fries": 76,
    "Rib": 33,
    "Taco": 57,
    "Pho": 19,
    "Potato": 3
}

#呈現詞彙與對應數量
print("Total unique words:", total_unique_words)
print("Word frequencies:")
for word, freq in word_frequencies.items():
    print(f"{word}: {freq}")

# 繪圖結果（matplotlib）
import matplotlib.pyplot as plt

words = list(word_frequencies.keys())
frequencies = list(word_frequencies.values())

plt.figure(figsize=(10, 6))
plt.bar(words, frequencies, color='skyblue')
plt.title("Word Frequencies")
plt.xlabel("Words")
plt.ylabel("Frequency")
plt.xticks(rotation=45)
plt.tight_layout()

#圖表
plt.show()

#繪圖結果：
plt.savefig("word_frequencies.png")
print("Bar chart saved as 'word_frequencies.png'")